# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9343e579bcda2b593f66d548a4f4ee8274fa43ddce0b9c74b04b1e2009ca25cb060e3c25c94b0aae307e060561426d1b2d64cca8c922cf826709ec77b3209a4

test:
  secret_key_base: a7d6d3852cbf5878fdd5d3d34d9ba09b0c11793d5fe55d4d833cdaf31b57f94557c33fcbcc074d77faf9119856008af58b010af831a4dcc593fc365b9fc14b8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
